name: C++ artifact demo

on:
  workflow_dispatch:

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Compile C++ program on Ubuntu
        run:
          g++ main.cpp -o hello

      - name: Upload Ubuntu executable
        uses: actions/upload-artifact@v6
        with:
          name: cpp-executable-ubuntu
          path: hello

  build-on-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Compile C++ program on Windows
        shell: bash
        run:
          g++ main.cpp -o hello.exe

      - name: Upload Windows executable
        uses: actions/upload-artifact@v6
        with:
          name: cpp-executable-windows
          path: hello.exe

  test-on-ubuntu:
    runs-on: ubuntu-latest
    needs: build-on-ubuntu

    steps:
      - name: Download Ubuntu executable
        uses: actions/download-artifact@v8
        with:
          name: cpp-executable-ubuntu
          path: downloaded

      - name: Run downloaded executable
        run: |
          chmod +x downloaded/hello
          ./downloaded/hello

  test-on-windows:
    runs-on: windows-latest
    needs: build-on-windows

    steps:
      - name: Download Windows executable
        uses: actions/download-artifact@v8
        with:
          name: cpp-executable-windows
          path: downloaded

      - name: Run downloaded executable
        shell: bash
        run: |
          chmod +x downloaded/hello.exe || true
          ./downloaded/hello.exe
